version: '3.1'

services:
  jenkins-base:
    build: jenkins-base
    ports:
     - '8080:8080'
    container_name: jenkins-master 
    volumes:
     - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
